### ISSUE TITLE
Improve the UI for better User Interaction and experience

### ISSUE THREAD

**Issue by SAQLAINAP** [Emulation-accurate/website#15]
The UI consists of colors that are not feasible for an easy look and vision, hence the theme needs to be updated.

![image](https://github.com/user-attachments/assets/e1c2c835-3e0b-4ff8-9847-1ca3afe44db6)

Also the footer needs to be fixed too.

**Comment by Emulation-accurate** [comment]
ok so  try to make it and raise PR
