### ISSUE TITLE
Create a sutaible background

### ISSUE THREAD

**Issue by Emulation-accurate** [Emulation-accurate/website#2]
**Create a sutaible background for landing page**

**Comment by AADESHak007** [comment]
Hey @Emulation-accurate I had a look the website and there are things that can be done to make the website look more interesting .
I would like to work on this issue .
Please assign this is issue to mw under hacktoberfest2024

**Comment by AADESHak007** [comment]
give me a days time I am working out the color scheme

**Comment by Emulation-accurate** [comment]
sure, take your time and give best output :)
